config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls", namespace="core")),
    path("reports/", include("reports.urls", namespace="reports")),
]

core/urls.py
from django.urls import path
from reports import views as report_views

app_name = "core"


urlpatterns = [
    path("", report_views.HomeView.as_view(), name="home"),
]

reports/urls.py
from django.urls import path
from . import views

app_name = "reports"

urlpatterns = [
    path("<str:company_pk>", views.ReportView.as_view(), name="list"),
    path(
        "<str:company_pk>/<str:department>/",
        views.DepartmentView.as_view(),
        name="department",
    ),
    path(
        "<str:company_pk>/<str:department>/<int:pk>",
        views.ReportDetail.as_view(),
        name="detail",
    ),
    path("<str:company_pk>/create", views.CreateReportView.as_view(), name="create"),
]

reports/models.py
from django.db import models


class AbstractItem(models.Model):

    """Abstract Item"""

    name = models.CharField("선택가능한 옵션", max_length=80)

    class Meta:
        abstract = True

    def __str__(self):
        return self.name


class CompanyName(AbstractItem):

    """CompanyName Model Definition"""

    class Meta:
        verbose_name = "사업장명"


class Department(AbstractItem):

    """Department Model Definition"""

    class Meta:
        verbose_name = "부서"


class Rater(AbstractItem):

    """Rater Model Definition"""

    class Meta:
        verbose_name_plural = "평가자"


class Process(AbstractItem):

    """Process Model Definition"""

    class Meta:
        verbose_name_plural = "공정명"


class Place(AbstractItem):

    """Place Model Definition"""

    class Meta:
        verbose_name_plural = "장소"


class RiskType(AbstractItem):

    """Place Model Definition"""

    class Meta:
        verbose_name_plural = "위험 분류"


class Factor(AbstractItem):

    """Place Model Definition"""

    class Meta:
        verbose_name_plural = "유해위험요인"


class AfterPlan(AbstractItem):

    """AfterPlan Model Definition"""

    class Meta:
        verbose_name_plural = "위험성 감소 대책 및 관리 방안"


class ReportContent(models.Model):

    """ReportContent Model Definition"""

    class Meta:
        verbose_name_plural = "리포트 리스트"

    risk_type = models.ForeignKey(
        "RiskType",
        related_name="risk_type",
        on_delete=models.SET_NULL,
        null=True,
        verbose_name="위험분류",
    )
    factor = models.ForeignKey(
        "Factor",
        related_name="factor",
        on_delete=models.SET_NULL,
        null=True,
        verbose_name="유해위험요인",
    )
    factor_source = models.TextField("유해위험요인 원인")
    row_basis = models.TextField("관련 근거")

    present_measures = models.TextField("현재의 안전보건 조치")
    present_frequency = models.IntegerField("현재 위험성 가능성")
    present_importance = models.IntegerField("현재 위험성 중대성")

    after_plan = models.ManyToManyField(
        "AfterPlan",
        related_name="after_plan",
        blank=True,
        verbose_name="위험성 감소 대책 및 관리 방안",
    )
    after_frequency = models.IntegerField("개선 후 위험성 가능성")
    after_importance = models.IntegerField("개선 후 위험성 중대성")

    improvement_date = models.DateField(("개선 예정일"))
    improvement_officer = models.CharField(
        "개선 책임자",
        max_length=20,
    )
    present_img = models.ImageField(
        upload_to="report_photos",
        verbose_name="개선 전 사진",
        blank=True,
    )
    after_img = models.ImageField(
        upload_to="report_photos",
        verbose_name="개선 후 사진",
        blank=True,
    )

    report = models.ForeignKey(
        "Report",
        related_name="report_content",
        on_delete=models.CASCADE,
        verbose_name="리포트",
    )

    def __str__(self):
        return str(self.risk_type)

    def present_rating_average(self):
        avg = self.present_frequency * self.present_importance
        return avg

    def after_rating_average(self):
        avg = self.after_frequency * self.after_importance
        return avg


class Report(models.Model):

    """Report Model Definition"""

    class Meta:
        verbose_name_plural = "리포트"

    last_update = models.DateTimeField(auto_now=True)
    company_name = models.ForeignKey(
        "CompanyName",
        related_name="company_name",
        on_delete=models.SET_NULL,
        null=True,
        verbose_name="사업장명",
    )
    department = models.ForeignKey(
        "Department",
        related_name="department",
        on_delete=models.SET_NULL,
        null=True,
        verbose_name="부서명",
    )
    rater = models.ManyToManyField(
        "Rater",
        related_name="rater",
        blank=True,
        verbose_name="평가자",
    )
    effective_date = models.DateField(("평가 일시"))
    process = models.ForeignKey(
        "Process",
        related_name="process",
        on_delete=models.SET_NULL,
        null=True,
        verbose_name="공정명",
    )
    place = models.ForeignKey(
        "Place",
        related_name="place",
        on_delete=models.SET_NULL,
        null=True,
        verbose_name="작업명 또는 장소",
    )

    def __str__(self):
        return str(self.company_name)

    def present_total_rating(self):
        all_report = self.report_content.all()
        all_ratings = 0
        for report in all_report:
            all_ratings += report.present_rating_average()
        return round(all_ratings / len(all_report), 1)

    def after_total_rating(self):
        all_report = self.report_content.all()
        all_ratings = 0
        for report in all_report:
            all_ratings += report.after_rating_average()
        return round(all_ratings / len(all_report), 1)

    present_total_rating.short_description = "개선 전 위험성 평균점수"
    after_total_rating.short_description = "개선 후 위험성 평균점수"

reports/forms.py
from django import forms
from django.forms import TextInput
from . import models


class CreateReportForm(forms.ModelForm):
    class Meta:
        model = models.Report
        fields = (
            "company_name",
            "department",
            "rater",
            "effective_date",
            "process",
            "place",
        )
        widgets = {
            "operation": TextInput(attrs={"placeholder": "작업내용"}),
        }

    def save(self, *args, **kwargs):
        report = super().save(commit=False)
        return report

        # "department": ModelChoiceField(
        #     queryset=models.DepartmentType.objects.all()
        # ),

reports/views.py
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import ListView, DetailView, FormView
from django.db.models import Q
from django.db.models import Avg

from reports import forms
from . import models


class HomeView(ListView):
    """HomeView Definition"""

    model = models.CompanyName
    paginate_by = 12
    paginate_orphans = 5
    template_name = "companys/company_list.html"
    context_object_name = "companys"


class ReportView(ListView):
    """ReportView Definition"""

    model = models.Report
    paginate_by = 12
    paginate_orphans = 5
    context_object_name = "reports"

    def get_context_data(self, **kwargs):
        context = super(ReportView, self).get_context_data(**kwargs)
        report = models.Report.objects.filter(
            company_name__name=self.kwargs.get("company_pk")
        )
        context["company_reports"] = report

        context["avg_present_frequency"] = report.aggregate(
            Avg("report_content__present_frequency")
        )
        context["avg_present_importance"] = report.aggregate(
            Avg("report_content__present_importance")
        )

        context["avg_after_frequency"] = report.aggregate(
            Avg("report_content__after_frequency")
        )
        context["avg_after_importance"] = report.aggregate(
            Avg("report_content__after_importance")
        )

        context["avg_present"] = round(
            context["avg_present_frequency"]["report_content__present_frequency__avg"]
            * context["avg_present_importance"][
                "report_content__present_importance__avg"
            ],
            2,
        )

        context["avg_after"] = round(
            context["avg_after_frequency"]["report_content__after_frequency__avg"]
            * context["avg_after_importance"]["report_content__after_importance__avg"],
            2,
        )

        return context


class DepartmentView(ListView):
    """ReportView Definition"""

    model = models.Report
    paginate_by = 12
    paginate_orphans = 5
    context_object_name = "department"
    template_name = "reports/departments/department_list.html"

    def get_context_data(self, **kwargs):
        context = super(DepartmentView, self).get_context_data(**kwargs)
        context["department_reports"] = models.Report.objects.filter(
            Q(company_name__name=self.kwargs.get("company_pk"))
            & Q(department__name=self.kwargs.get("department"))
        )
        return context


class ReportDetail(DetailView):
    """ReportDetail Definition"""

    model = models.Report
    context_object_name = "report"


class CreateReportView(FormView):
    """ReportCreate View"""

    form_class = forms.CreateReportForm
    template_name = "reports/report_create.html"

    def form_valid(self, form):
        report = form.save()
        report.save()
        form.save_m2m()
        return redirect(reverse("core:home"))

templates/reports/report_create.html
{% extends "base.html" %}
{% block page_title %}
Report Detail
{% endblock page_title %}
{% block content %}

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>
<link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css"/>
<link rel="stylesheet" href="/static/css/common.css">

<form method="POST" class="w-full" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="field_wrap grid grid-cols-5 gap-4">
        {% for field in form|slice:":3" %}
        <div class="input w-full">
            <p>{{field.label}}</p>
            {{field}}
        </div>
        {% endfor %}
    </div>
    
    <button type="submit">보고서 생성</button>
</form>   


<script>
    $('#id_effective_date').datepicker({
        uiLibrary: 'bootstrap'
    });
</script>

<style>

    /* input 기본 스타일 초기화 */
input {
    -webkit-appearance: none;
       -moz-appearance: none;
            appearance: none;
}

/* IE10 이상에서 input box 에 추가된 지우기 버튼 제거 */
input::-ms-clear { display: none; }

/* input type number 에서 화살표 제거 */
input[type='number']::-webkit-inner-spin-button,
input[type='number']::-webkit-outer-spin-button {
    -webkit-appearance: none;
       -moz-appearance: none;
            appearance: none;
}
/* Select box 스타일 초기화 */ 
select {
    -webkit-appearance: none;
       -moz-appearance: none;
            appearance: none;
}

/* IE 에서 Select box 화살표 제거 */ 
select::-ms-expand { display: none; }

.field_wrap>div{
    margin-top: 30px;
}
.field_wrap div:nth-child(6){
    grid-column: span 2 / span 2;
}
.field_wrap div:nth-child(10){
    grid-column: span 2 / span 2;
}
.input input,select{
    width: 30rem;
}
.input input,.input select,.input textarea{
    
    box-sizing: border-box;
    border-radius: 3px;
    padding: 1rem 3rem;
}
.input input:focus,.input select:focus,.input textarea:focus{
    outline: 2px solid #14B8A6;
}
.gj-datepicker.gj-datepicker-bootstrap.gj-unselectable.input-group{
display: flex;
}
.gj-datepicker.gj-datepicker-bootstrap.gj-unselectable.input-group input{
width: 30rem;
}
</style>
{% endblock content %}

templates/reports/report_detail.html
{% extends "base.html" %}
{% block page_title %}
Report Detail
{% endblock page_title %}
{% block content %}

    <div class="bg-white rounded-[4.5rem] w-full h-[65rem] mt-10 pl-24">
        <div class="flex justify-between">
            <div class="w-[73%] pt-20 pr-24">
                <div class="flex justify-between">
                    <div>
                        <h4 class="leading-none font-semibold tracking-tight text-[3.2rem] font-sans	text-gray-900">Credit Report</h4>
                        <span class="block text-lg mt-2 ml-1 text-gray-700">{{report.company}} / {{report.department}}</span>
                    </div>
                    <div class="mt-4">
                        {% if report.after_dangerous < 3 %}
                        <p class="inline-block px-10 py-[0.8rem] rounded-lg text-lg font-medium bg-green-500 text-white">낮음</p>
                        {% elif report.after_dangerous < 5 %}
                        <p class="inline-block px-10 py-[0.8rem] rounded-lg text-lg font-medium bg-violet-500 text-white">보통</p>
                        {% else %}
                        <p class="inline-block px-10 py-[0.8rem] rounded-lg text-lg font-medium bg-rose-500 text-white">높음</p>
                        {% endif %}
                        <div class="inline-block bg-gray-200 ml-3 text-lg text-center px-5 py-[0.8rem] rounded-lg  text-gray-700"><i class="fa-solid fa-calendar-days mr-2"></i> {{report.effective_date}}</div>
                        <div class="inline-block bg-gray-200 ml-3 text-lg cursor-pointer text-center px-5 py-[0.8rem] rounded-lg"><i class="fa-solid fa-print text-gray-500 hover:text-gray-900 hover:duration-150"></i></div>
                    </div>
                </div>
                <!-- Lift Chart Section  -->
                {% include 'mixins/report_left_chart.html' with report=report %}
                <div class="flex items-center mt-12">
                    <h5 class="leading-none font-normal tracking-tight text-3xl font-sans text-gray-800">Credit Factors</h5>
                    <span class="ml-3 mt-1 block bg-gray-300 text-center w-5 h-5 rounded-[0.2rem] text-white cursor-pointer rotate-45"><span class="block text-sm font-medium rotate-[315deg]">i</span></span>
                </div>
                <ul class="grid grid-cols-3 gap-10 mt-8">
                    <li class="border rounded-3xl px-10 py-8">
                        <i class="text-violet-500 text-2xl font-bold">{{report.after_frequency}} Point</i>
                        <p class="mt-2">유해요인의 빈도 수 <span class="text-gray-400 text-sm">(가능성)</span></p>
                    </li>
                    <li class="border rounded-3xl px-10 py-8">
                        <i class="text-violet-500 text-2xl font-bold">{{report.after_importance}} Point</i>
                        <p class="mt-2">유해요인의 중대성 <span class="text-gray-400 text-sm">(강도)</span></p>
                    </li>
                    <li class="border rounded-3xl px-10 py-8">
                        <i id="dangerous" class="text-violet-500 text-2xl font-bold"></i>
                        <p class="mt-2">유해요인의 위험성 추정 <span class="text-gray-400 text-sm">(위험성 = 빈도 x 강도)</span></p>
                    </li>
                </ul>
            </div>
            <div class="bg-slate-200 w-[27%] rounded-bl-[4.5rem] rounded-tr-[4.5rem] h-[56.8rem] px-16 pb-20">
                <a class="block text-right pt-10" href="{% url 'core:home' %}"><i class="fa-solid fa-arrow-right-from-bracket text-3xl text-gray-600 hover:text-gray-900 hover:duration-150"></i></a>
                <h5 class="leading-none font-normal tracking-tight text-3xl font-sans">Credit Factors</h5>
                <div class="mt-3 text-xl font-light text-gray-600">Total : <span class="inline-block ml-2 font-medium tracking-tight text-gray-800 text-2xl font-sans" id="dangerous2"></span></div>
                <!-- Right Chart Section  -->
                {% include 'mixins/report_right_chart.html' with report=report %}
                <ul class="mt-7">
                    <li class="flex items-center"><span class="blcok ml-3 mt-1 block bg-[#008ffb] text-center w-5 h-5 rounded-[0.2rem] text-white rotate-45"><span class="block text-sm font-medium rotate-[315deg]">i</span></span> <p class="text-xl ml-5 font-semibold mt-[3px]">안녕</p></li>
                    <li class="flex items-center"><span class="blcok ml-3 mt-4 block bg-[#008ffb] text-center w-5 h-5 rounded-[0.2rem] text-white rotate-45"><span class="block text-sm font-medium rotate-[315deg]">i</span></span> <p class="text-xl ml-5 font-semibold mt-[3px]">안녕</p></li>
                    <li class="flex items-center"><span class="blcok ml-3 mt-1 block bg-[#008ffb] text-center w-5 h-5 rounded-[0.2rem] text-white rotate-45"><span class="block text-sm font-medium rotate-[315deg]">i</span></span> <p class="text-xl ml-5 font-semibold mt-[3px]">안녕</p></li>
                </ul>
            </div>
        </div>
    </div>

    <div class="absolute z-[-10] top-[-20px] left-[-90px] bg-green-500 w-[30%] h-[23vh] rounded-full"></div>
    <div class="absolute z-[-10] bottom-0 right-[-120px] bg-violet-600 w-[30%] h-[16vh] rounded-full"></div>

    <script>
        frequency = Number("{{report.after_frequency}}")
        importance = Number("{{report.after_importance}}")
        dangerous = frequency * importance + " Point"
        document.querySelector("#dangerous").innerText = dangerous
        document.querySelector("#dangerous2").innerText = dangerous
    </script>

   

{% endblock content %}

templates/reports/report_list.html
{% extends "base.html" %}
{% block page_title %}
Report List
{% endblock page_title %}
{% block content %}

<!-- <a id="create_report">보고서 추가하기</a> -->
<div class="px-52">
    <h3 class="text-3xl font-semibold mb-10 mt-16">Dashboard</h3>
    <div class="flex justify-between">
        <ul class="bg-white h-[530px] w-[360px] py-7">
            <li class="flex items-center">
                <div id="chart1" class="relative w-40">
                    <p class="absolute left-[40%] top-[37%] text-lg font-semibold text-[#1E3A8A]">78%</p>
                </div>
                <div class="pb-4 ml-3">
                    <h6 class="text-gray-600 font-medium">개선 전 중요도</h6>
                    <p class="text-2xl font-semibold mt-1">{{avg_present_frequency.report_content__present_frequency__avg}}</p>
                </div>
                
            </li>
            <li class="flex items-center mt-2">
                <div id="chart2" class="relative w-40">
                    <p class="absolute left-[40%] top-[37%] text-lg font-semibold text-[#22c55e]">78%</p>
                </div>
                <div class="pb-4 ml-3">
                    <h6 class="text-gray-600 font-medium">개선 전 중요도</h6>
                    <p class="text-2xl font-semibold mt-1">{{avg_present_importance.report_content__present_importance__avg}}</p>
                </div>
            </li>
            <li class="flex items-center mt-2">
                <div id="chart3" class="relative w-40">
                    <p class="absolute left-[40%] top-[37%] text-lg font-semibold text-[#F59E0B]">78%</p>
                </div>
                <div class="pb-4 ml-3">
                    <h6 class="text-gray-600 font-medium">개선 후 중요도</h6>
                    <p class="text-2xl font-semibold mt-1">{{avg_after_frequency.report_content__after_frequency__avg}}</p>
                </div>
            </li>
            <li class="flex items-center mt-2">
                <div id="chart4" class="relative w-40">
                    <p class="absolute left-[40%] top-[37%] text-lg font-semibold text-[#6b21a8]">78%</p>
                </div>
                <div class="pb-4 ml-3">
                    <h6 class="text-gray-600 font-medium">개선 후 중요도</h6>
                    <p class="text-2xl font-semibold mt-1">{{avg_after_importance.report_content__after_importance__avg}}</p>
                </div>
            </li>
        </ul>
        <div class="bg-white h-[530px] w-[750px]`">
            <div id="chart5" class="w-[750px]"></div>
        </div>
        <div class="bg-white h-[530px] w-[650px]">
            <div id="chart6" class="w-[620px]"></div>
        </div>
    </div>
    <h3 class="text-2xl font-normal mb-10 mt-16">Interface Summary</h3>
    <div class="grid grid-cols-4 gap-7">
        {% for report in company_reports %}
        <div class="bg-white px-8 py-4 rounded-lg shadow-slate-200 shadow duration-150 hover:shadow-xl hover:shadow-slate-200">
            <div class="flex items-center justify-between">
                <a href="/reports/{{report.company_name}}/{{report.department}}">
                    <h4 class="font-light text-xl text-gray-500">{{report.company_name}}</h4>
                    <h4 class="text-2xl text-gray-900 mb-4">{{report.department}}</h4>
                </a>
                <div>
                    {% if report.after_total_rating < 3 %}
                        <p class="rounded-xl py-[0.1rem] pl-3 pr-2 bg-green-500 text-white">낮음<i class="fa-solid fa-circle-check ml-1"></i></p>
                    {% elif report.after_total_rating < 5 %}
                        <p class="rounded-xl py-[0.1rem] pl-3 pr-2 bg-violet-500 text-white">보통<i class="fa-solid fa-circle-exclamation ml-1"></i></p>
                    {% else %}
                        <p class="rounded-xl py-[0.1rem] pl-3 pr-2 bg-rose-500 text-white">높음<i class="fa-solid fa-circle-exclamation ml-1"></i></p>
                    {% endif %}
                </div>
            </div>

            <div class="flex mt-3">
                <div>
                    <h6 class="text-gray-700 font-light">위험성 평균</h6>
                    <p class="text-rose-600 font-semibold">{{report.present_total_rating}}</p>
                </div>
                <div class="ml-20">
                    <h6 class="text-gray-700 font-light">위험성 평균</h6>
                    <p class="font-semibold">{{report.after_total_rating}}</p>
                </div>
            </div>
            <div class="mt-9 flex justify-between items-center">
                <p class="tracking-tighter text-xs">
                    <span class="block tracking-normal text-gray-500 font-light">Last Update</span>
                    {% load humanize %}
                    {{ report.last_update | naturaltime }}
                </p>
                <ul>
                    <a href="#"><i class="fa-solid fa-pen-to-square text-lg text-gray-700"></i></a>
                    <a class="mx-1" href="#"><i class="fa-solid fa-magnifying-glass text-lg text-gray-700"></i></a>
                    <a href="#"><i class="fa-solid fa-trash-can text-lg text-gray-700"></i></a>
                </ul>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

<style>
    hi{
        background-color: #c999f1;
    }
</style>
<script>


const present_frequency = Number("{{avg_present_frequency.report_content__present_frequency__avg}}")
const present_importance = Number("{{avg_present_importance.report_content__present_importance__avg}}")
const after_frequency = Number("{{avg_after_frequency.report_content__after_frequency__avg}}")
const after_importance = Number("{{avg_after_importance.report_content__after_importance__avg}}")
const avg_present = Number("{{avg_present}}")
const avg_after = Number("{{avg_after}}")


var options = {
    series: [present_frequency, Number((3 - Number(present_frequency)).toPrecision(1)) ],
    chart: {
    type: 'donut',
    },
    dataLabels: {
    enabled: false,
    },
    colors: ['#1E3A8A',"#9da9cd"],
    labels: ['빈도 수', '총 점수'],
    legend: {
      show: false,
    }
};
var chart = new ApexCharts(document.querySelector("#chart1"), options);
chart.render();
var options = {
    series: [present_importance, Number((3 - Number(present_importance)).toPrecision(1))],
    chart: {
    type: 'donut',
    },
    dataLabels: {
    enabled: false,
    },
    colors: ['#22c55e',"#72e09a"],
    labels: ['빈도 수', '총 점수'],
    legend: {
      show: false,
    }
};
var chart2 = new ApexCharts(document.querySelector("#chart2"), options);
chart2.render();
var options = {
    series: [after_frequency, Number((3 - Number(after_frequency)).toPrecision(1))],
    chart: {
    type: 'donut',
    },
    dataLabels: {
    enabled: false,
    },
    colors: ['#F59E0B',"#fad9a1"],
    labels: ['빈도 수', '총 점수'],
    legend: {
      show: false,
    }
};
var chart3 = new ApexCharts(document.querySelector("#chart3"), options);
chart3.render();
var options = {
    series: [after_frequency, Number((3 - Number(after_importance)).toPrecision(1))],
    chart: {
    type: 'donut',
    },
    dataLabels: {
    enabled: false,
    },
    colors: ['#6b21a8',"#c999f1"],
    labels: ['빈도 수', '총 점수'],
    legend: {
      show: false,
    }
};
var chart4 = new ApexCharts(document.querySelector("#chart4"), options);
chart4.render();

var options = {
          series: [{
          name: 'series1',
          data: [31, 40, 28, 51, 42, 109, 100]
        }, {
          name: 'series2',
          data: [11, 32, 45, 32, 34, 52, 41]
        }],
          chart: {
          height: 350,
          type: 'area'
        },
        dataLabels: {
          enabled: false
        },
        stroke: {
          curve: 'smooth'
        },
        xaxis: {
          type: 'datetime',
          categories: ["2018-09-19T00:00:00.000Z", "2018-09-19T01:30:00.000Z", "2018-09-19T02:30:00.000Z", "2018-09-19T03:30:00.000Z", "2018-09-19T04:30:00.000Z", "2018-09-19T05:30:00.000Z", "2018-09-19T06:30:00.000Z"]
        },
        tooltip: {
          x: {
            format: 'dd/MM/yy HH:mm'
          },
        },
        };
var chart6 = new ApexCharts(document.querySelector("#chart6"), options);
chart6.render();


</script>

<script>
    var link =  document.location.href;
    createReport = document.getElementById('create_report')
    createReport.setAttribute("href",link+"/create")
</script>

{% endblock content %}